### ISSUE TITLE
Build a card widget

### ISSUE THREAD

**Issue by danielphilipjohnson** [vishal-codes/react-widgets#111]
I'm happy to build the basics of a card component. Then create some good first issues such as providing props for the title, image and other things. As well as creating good first issues to add color variants to the card component.

I think it will be nice to get others involved in building some basic components in react for now. Then later create more additional functionality.

Let me know if that's okay?

**Comment by vishal-codes** [comment]
> I'm happy to build the basics of a card component. Then create some good first issues such as providing props for the title, image and other things. As well as creating good first issues to add color variants to the card component.
> 
> I think it will be nice to get others involved in building some basic components in react for now. Then later create more additional functionality.
> 
> Let me know if that's okay?

Thank's for showing interest but for the time being can we keep this in [discussions](https://github.com/vishal-codes/react-widgets/discussions) .Let me know if u are comfortable with this so that I can close this issue and discuss more about in [discussions](https://github.com/vishal-codes/react-widgets/discussions).

**Comment by danielphilipjohnson** [comment]
Yes happy to discuss this in discussion :)

**Comment by vishal-codes** [comment]
> Yes happy to discuss this in discussion :)

Okay so I'll close this issue for the time being
